[package]
name = "day3"
version = "0.1.0"
authors = ["Achim Winter <achim.winter95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"